web_robot_api:
    resource: "@WebRobotApiBundle/Resources/config/routing.yml"
    prefix:   /

web_robot_freelance:
    resource: "@WebRobotFreelanceBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"