web_robot_freelance_contacts:
    resource: "@WebRobotFreelanceBundle/Resources/config/routing/contact.yml"
    prefix:   /contacts

web_robot_freelance_projects:
    resource: "@WebRobotFreelanceBundle/Resources/config/routing/project.yml"
    prefix:   /projects

web_robot_freelance_clients:
    resource: "@WebRobotFreelanceBundle/Resources/config/routing/client.yml"
    prefix:   /clients

homepage:
    path:     /
    defaults: { _controller: WebRobotFreelanceBundle:Default:index }