homepage:
    path:     /
    defaults: { _controller: WebRobotFreelanceBundle:Default:index }

clients:
    resource: "@WebRobotFreelanceBundle/Controller/"
    type:     annotation
    prefix:   /

projects:
    resource: "@WebRobotFreelanceBundle/Controller/"
    type:     annotation
    prefix:   /

sessions:
    resource: "@WebRobotFreelanceBundle/Controller/"
    type:     annotation
    prefix:   /