projects:
    type:       rest
    resource:   "@WebRobotApiBundle/Controller/ProjectController.php"

clients:
    type:       rest
    resource:   "@WebRobotApiBundle/Controller/ClientController.php"