projects:
    type:       rest
    resource:   "@WebRobotApiBundle/Controller/ProjectController.php"
    prefix:     /project

clients:
    type:       rest
    resource:   "@WebRobotApiBundle/Controller/ClientController.php"