projects:
    path:     /
    defaults: { _controller: "WebRobotFreelanceBundle:Project:index" }

projects_show:
    path:     /{id}/show
    defaults: { _controller: "WebRobotFreelanceBundle:Project:show" }

projects_new:
    path:     /new
    defaults: { _controller: "WebRobotFreelanceBundle:Project:new" }

projects_create:
    path:     /create
    defaults: { _controller: "WebRobotFreelanceBundle:Project:create" }
    methods:  POST

projects_edit:
    path:     /{id}/edit
    defaults: { _controller: "WebRobotFreelanceBundle:Project:edit" }

projects_update:
    path:     /{id}/update
    defaults: { _controller: "WebRobotFreelanceBundle:Project:update" }
    methods:  [POST, PUT]

projects_delete:
    path:     /{id}/delete
    defaults: { _controller: "WebRobotFreelanceBundle:Project:delete" }
    methods:  [POST, DELETE]
